language: r
sudo: false
cache: packages
warnings_are_errors: false

addons:
  apt:
    packages:
      - tcl8.5-dev
      - tk8.5-dev
      
r_github_packages:
  - jimhester/covr
  - yonicd/covrpage
  
before_install:
  - Rscript -e 'install.packages(c("nlme"),lib="/home/travis/R-bin/lib/R/library/")'

after_success:
  - Rscript -e 'covr::coveralls()'
  - Rscript -e 'devtools::install(); covrpage::covrpage_ci()'
  - Rscript -e 'pkgdown::build_site()'

notifications:
  email:
    on_success: change
    on_failure: always

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
